language: ruby
cache: bundler

rvm:
  - ruby-head
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8

branches:
  only:
    - master
    - development

env:
  - BUNDLE_VERSION="~> 1.0"

before_install:
  - gem update --system
  - gem install bundler --version "$BUNDLE_VERSION"
  - gem install rubocop

before_script: rubocop --fail-level=W
